# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43cff0c9a2189cc55505125ea74e8556515fe7fa4581d86b905a1516fd6e1eeebcf229f0eeb6abbe2529bdefc026add357a3397dbd8d0e35103bfd0b2990acbe

test:
  secret_key_base: dbefcceace00a2579658da8d321e334d09fa4764c15232c4c4ed20118eaf445a16d6de82ba76f3b3252643c21ceda997b59bf59390a57b8c6daf71c98032124f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
